# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
  - hooks:
      - args:
          - >-
            markdown
          - >-
            document
          - >-
            --output-file
          - >-
            README.md
        id: terraform-docs-go
    repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
